### ISSUE TITLE
Dot-Examples OTA Broke the Board

### ISSUE THREAD

**Issue by phantomlinux** [MultiTechSystems/dot-examples#1]
Hi All, 

Can someone help us with this issue? We have xdot mounted on our own custom PCB as well and integrated with Bosch BME sensors. All the while we were using the code snippet examples from [mbed](https://github.com/ARMmbed/mbed-os-example-lorawan)but we couldn't get enough deepsleep from there. So we decided to use xdot's own library.

But after the first flash on our built OTA_EXAMPLE, the 2nd board stopped working and cannot be flash anymore. No error from DAPLink xdot, but the file is not flashing into the board. We try simple led flashing code, mbed lora samples and our old bin file.. all of them couldn't be flashed in.

The thing is that the unit from Usb Development Xdot works fine. 

Below is another person with similar experience few years back
Ref: http://www.multitech.net/developer/forums/topic/xdot-serial-uart-problems/

**Comment by bryond** [comment]
Sometimes the xDot processor can get into a state where it doesn't respond to reset request from the JTAG. This can happen if the custom code on the xDot ran into an error and crashed.
With the USB development boards, you can hold the reset button while starting the firmware flash, releasing the reset button immediately after initializing the flash. Since this is mounted on a PCB board this may not be possible.

Another option is to try uploading the firmware using the bootloader (if the bootloader was included in the previous firmware). If you could load a known working firmware such as the AT firmware through the bootloader, you may be able to load your firmware again using JTAG.

Please see the "Updating Firmware Using the xDot Bootloader" section in the xDot Developer Guide starting on page 12 for more information on this:
https://www.multitech.com/documents/publications/manuals/s000645.pdf

To get the xDot application firmware files (for xDot bootloader upgrades), please go to the link below, scroll down to the xDot section and click on the "xDot Application only images" link:
http://www.multitech.net/developer/downloads/

If this still doesn't help, then please create a case on the Multi-Tech Support portal at support.multitech.com

**Comment by phantomlinux** [comment]
Hi thank you for your reply! 

After multiple of tries today,  we actually found out that our compiled Dot-Examples reset the dev eui to 00 00 00 00 00 00 00 00 resulting the board stop working and couldn't send any message to the gateway. 

Already submitted a case to MultiTech support. 

By any chance if we can set the device id our own ? Tried the mdot.h's dot->setDeviceId(); no luck on that

**Comment by reissjason** [comment]
When using JTAG utilities do not use the erase flash option, this will remove the all identification and configuration information in the eeprom. The eeprom is a part of flash just after the application space.
